dask-gateway:
  gateway:
    auth:
      jupyterhub:
        apiToken: token1 # replace this 
        apiUrl: http://proxy-public/hub/api
      type: jupyterhub

jupyterhub:
  hub:
    config:
      GenericOAuthenticator:
        client_id: client_id # replace this
        client_secret: client_secret # replace this
        oauth_callback_url: https://pangeo-eosc.vm.fedcloud.eu/hub/oauth_callback # replace this with your DNS name
        authorize_url: https://aai-dev.egi.eu/auth/realms/egi/protocol/openid-connect/auth
        token_url: https://aai-dev.egi.eu/auth/realms/egi/protocol/openid-connect/token
        userdata_url: https://aai-dev.egi.eu/auth/realms/egi/protocol/openid-connect/userinfo
        login_service: EGI Check-In
        scope:
          - openid
          - email
          - profile
          - eduperson_entitlement
        username_key: preferred_username
        userdata_params:
          state: state
        allowed_groups:
          - urn:mace:egi.eu:group:vo.pangeo.eu:role=member#aai.egi.eu
        claim_groups_key: eduperson_entitlement
      JupyterHub:
        authenticator_class: generic-oauth
    services:
      dask-gateway:
        apiToken: token1 # replace this

  proxy:
    secretToken: token2 # replace this 
